<?php

/**
 * @file
 * Main functions and hook implementations for the Invoicing Client module.
 */

include_once 'client.features.inc';

/**
 * Implements hook_entity_info().
 */
function client_entity_info() {
  $info = array();

  $entity_info['client'] = array(
    'label' => t('Client'),
    'plural label' => t('Clients'),
    'entity class' => 'Client',
    'controller class' => 'EntityAPIController',
    'base table' => 'client',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'cid',
      'bundle' => 'type',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'access callback' => 'client_access',
  );

  // Add bundle info but bypass entity_load() as we cannot use it here.
  $types = db_select('client_type', 'ict')
    ->fields('ict', array('type', 'name'))
    ->execute()
    ->fetchAllKeyed();

  foreach ($types as $type => $name) {
    $entity_info['client']['bundles'][$type] = array(
      'label' => $name,
      'admin' => array(
        'path' => 'admin/structure/clients/manage/%client_type',
        'real path' => 'admin/structure/clients/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer clients'),
      ),
    );
  }

  $entity_info['client_type'] = array(
    'label' => t('Client type'),
    'plural label' => t('Client types'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIControllerExportable',
    'base table' => 'client_type',
    'fieldable' => FALSE,
    'bundle of' => 'client',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'type',
      'name' => 'type',
      'label' => 'name',
    ),
    'access callback' => 'client_type_access',
    'label callback' => 'client_type_label',
    'module' => 'client',
    'admin ui' => array(
      'path' => 'admin/structure/clients',
      'file' => 'client.admin.inc',
      'controller class' => 'EntityDefaultUIController',
    ),
  );

  return $entity_info;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function client_entity_property_info_alter(&$info) {
  // Augment the default information that is provided by entityPropertyInfo().
  // @see EntityDefaultMetadataController::entityPropertyInfo()
  $properties = &$info['client']['properties'];

  $properties['type']['description'] = t('The client type');
  $properties['type']['options list'] = 'client_type_get_names';
  $properties['type']['required'] = TRUE;
  $properties['type']['setter callback'] = 'entity_property_verbatim_set';
  $properties['type']['setter permission'] = 'administer clients';

  $properties['name']['description'] = t('The name of the client.');
  $properties['name']['required'] = TRUE;
  $properties['name']['setter callback'] = 'entity_property_verbatim_set';

  $properties['created']['label'] = t('Date created');
  $properties['created']['description'] = t('The date the client was created.');
  $properties['created']['type'] = 'date';
  $properties['created']['setter callback'] = 'entity_property_verbatim_set';
  $properties['created']['setter permission'] = 'administer clients';

  $properties['changed']['label'] = t('Date changed');
  $properties['changed']['description'] = t('The date the client was most recently updated.');
  $properties['changed']['type'] = 'date';

  $properties['is_new']['label'] = t('Is new');
  $properties['is_new']['description'] = t('Whether the client is new and not saved to the database yet.');
  $properties['is_new']['type'] = 'boolean';
  $properties['is_new']['getter callback'] = 'client_entity_metadata_get_properties';
}

/**
 * Implements hook_menu().
 */
function client_menu() {
  $items = array();

  // We only support one basic client type for the moment. This may be extended
  // in the future.
  $client_type = client_type_load('client');
  $items['client/add'] = array(
    'title' => 'Add client',
    'page callback' => 'client_add_page',
    'page arguments' => array($client_type),
    'access callback' => 'client_access',
    'access arguments' => array('create', $client_type),
    'file' => 'client.pages.inc',
  );

  $items['client/%client/edit'] = array(
    'title' => 'Edit',
    'page callback' => 'client_edit_page',
    'page arguments' => array(1),
    'access callback' => 'client_access',
    'access arguments' => array('update', 1),
    'type' => MENU_LOCAL_TASK,
    'file' => 'client.pages.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function client_permission() {
  $permissions = array(
    'administer client types' => array(
      'title' => t('Administer client types'),
      'description' => t('Create and delete fields for client types, and set their permissions.'),
    ),
    'administer clients' => array(
      'title' => t('Administer clients'),
      'description' => t('Edit and delete all clients'),
    ),
  );

  // Generate permissions per client type.
  foreach (client_get_types() as $type) {
    $permissions += array(
      "edit any $type->type client" => array(
        'title' => t('%type_name: Edit any client', array('%type_name' => $type->name)),
      ),
      "view any $type->type client" => array(
        'title' => t('%type_name: View any client', array('%type_name' => $type->name)),
      ),
    );
  }

  return $permissions;
}

/**
 * Implements hook_field_extra_fields().
 */
function client_field_extra_fields() {
  $extra_fields = array();

  foreach (client_get_types() as $client_type) {
    $extra_fields['client'][$client_type->type] = array(
      'form' => array(
        'name' => array(
          'label' => t('Name'),
          'description' => t('The name of the client'),
          'weight' => -5,
        ),
      ),
    );
  }

  return $extra_fields;
}

/**
 * Determines whether the given user has access to a client.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param object $client
 *   Optionally a client or a client type to check access for. If nothing is
 *   given, access for all clients is determined.
 * @param object $account
 *   Optional, a user object representing the user for whom the operation is to
 *   be performed. Determines access for a user other than the current user.
 *
 * @return boolean
 *   TRUE if the operation may be performed, FALSE otherwise.
 */
function client_access($op, $client = NULL, $account = NULL) {
  if (user_access('administer clients', $account)) {
    return TRUE;
  }
  if (isset($client)) {
    $op = $op == 'view' ? 'view' : 'edit';
    return user_access("$op any $client->type client", $account);
  }

  return FALSE;
}

/**
 * Access callback for Entity API exportables for client types.
 */
function client_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer client types', $account);
}

/**
 * Returns an array of client types, keyed by the type name.
 *
 * @return array
 *   An array of client types.
 */
function client_get_types() {
  $types = &drupal_static(__FUNCTION__);

  if (!$types) {
    $types = db_select('client_type', 'ict')
      ->fields('ict')
      ->execute()
      ->fetchAllAssoc('type');
  }

  return $types;
}

/**
 * Returns a client type by type name.
 *
 * @param string $type
 *   The machine readable name of the client type.
 *
 * @return Entity
 *   A client type entity, or FALSE if the client type does not exist.
 */
function client_type_load($type) {
  $types = client_get_types();

  return !empty($types[$type]) ? $types[$type] : FALSE;
}

/**
 * Returns a list of client type machine names.
 *
 * @return array
 *   An indexed array of client type machine names.
 */
function client_type_get_names() {
  return array_keys(client_get_types());
}

/**
 * Loads clients from the database.
 *
 * This function should be used whenever you need to load more than one client
 * from the database. Clients are loaded into memory and will not require
 * database access if loaded again during the same page request.
 *
 * @see entity_load()
 * @see EntityFieldQuery
 *
 * @param $cids
 *   An array of client IDs.
 * @param $reset
 *   Whether to reset the internal cache.
 *
 * @return
 *   An array of client objects indexed by cid.
 */
function client_load_multiple($cids = array(), $reset = FALSE) {
  return entity_load('client', $cids, array(), $reset);
}

/**
 * Loads a client object from the database.
 *
 * @param $cid
 *   The client ID.
 * @param $reset
 *   Whether to reset the cache.
 *
 * @return
 *   A fully-populated client object, or FALSE if the client is not found.
 */
function client_load($cid = NULL, $reset = FALSE) {
  $cids = isset($cid) ? array($cid) : array();
  $clients = client_load_multiple($cids, $reset);

  return $clients ? reset($clients) : FALSE;
}

/**
 * Deletes a client.
 */
function client_delete(Client $client) {
  $client->delete();
}

/**
 * Deletes multiple clients.
 *
 * @param $cids
 *   An array of client IDs.
 */
function client_delete_multiple(array $cids) {
  entity_get_controller('client')->delete($cids);
}

/**
 * Creates a client object.
 */
function client_create($values = array()) {
  return entity_get_controller('client')->create($values);
}

/**
 * Saves a client to the database.
 *
 * @param $client
 *   The client object.
 */
function client_save(Client $client) {
  return $client->save();
}

/**
 * Implements callback_entity_info_uri().
 */
function client_uri(Client $client){
  return array(
    'path' => 'client/' . $client->cid,
  );
}

/**
 * Title callback: Returns the title of the client.
 *
 * @param $client
 *   The client object.
 *
 * @return
 *   An unsanitized string that is the title of the client.
 *
 * @see client_menu()
 */
function client_page_title($client) {
  return $client->name;
}

/**
 * Creates a client type.
 *
 * @param string $type
 *   The machine readable name of the client type.
 * @param string $name
 *   The human readable name of the client type.
 */
function client_type_create($type, $name) {
  db_insert('client_type')
    ->fields(array(
      'type' => $type,
      'name' => $name,
    ))
    ->execute();
}

/**
 * Callback for getting client properties.
 *
 * @see client_entity_property_info()
 */
function client_entity_metadata_get_properties(Client $client, array $options, $name, $entity_type, $info) {
  switch ($name) {
    case 'is_new':
      return empty($client->cid) || !empty($client->is_new);
  }
}

/**
 * The class used for client entities.
 */
class Client extends Entity {

  /**
   * The primary identifier for a client.
   */
  public $cid;

  /**
   * The type of this client.
   */
  public $type;

  /**
   * The name of the client.
   */
  public $name;

  /**
   * The Unix timestamp when the client was created.
   */
  public $created;

  /**
   * The Unix timestamp when the client was most recently saved.
   */
  public $changed;

  /**
   * {@inheritdoc}
   */
  public function save() {
    // Set created and changed values. Only set the created value if it is new.
    if (empty($this->created) && (!empty($this->is_new) || !$this->cid)) {
      $this->created = REQUEST_TIME;
    }
    $this->changed = REQUEST_TIME;

    parent::save();
  }
}
