<?php

/**
 * @file
 * Main functions and hook implementations for the Invoicing Line Item module.
 */

include_once 'line_item.features.inc';

/**
 * Implements hook_entity_info().
 */
function line_item_entity_info() {
  $entity_info = array();

  $entity_info['line_item'] = array(
    'label' => t('Line item'),
    'plural label' => t('Line items'),
    'entity class' => 'LineItem',
    'controller class' => 'LineItemAPIController',
    'base table' => 'line_item',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'lid',
      'bundle' => 'type',
    ),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'label callback' => 'line_item_label',
    'uri callback' => 'line_item_uri',
    'access callback' => 'line_item_access',
    'module' => 'line_item',
    'inline entity form' => array(
      'controller' => 'LineItemInlineEntityFormController',
    ),
  );

  // Add bundle info but bypass entity_load() as we cannot use it here.
  $types = db_select('line_item_type', 'lit')
    ->fields('lit', array('type', 'name'))
    ->execute()
    ->fetchAllKeyed();

  foreach ($types as $type => $name) {
    $entity_info['line_item']['bundles'][$type] = array(
      'label' => $name,
      'admin' => array(
        'path' => 'admin/structure/line_items/manage/%line_item_type',
        'real path' => 'admin/structure/line_items/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer line items'),
      ),
    );
  }

  $entity_info['line_item_type'] = array(
    'label' => t('Line item type'),
    'plural label' => t('Line item types'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIControllerExportable',
    'base table' => 'line_item_type',
    'fieldable' => FALSE,
    'bundle of' => 'line_item',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'type',
      'name' => 'type',
      'label' => 'name',
    ),
    'access callback' => 'line_item_type_access',
    'label callback' => 'line_item_type_label',
    'module' => 'line_item',
    'admin ui' => array(
      'path' => 'admin/structure/line_items',
      'file' => 'line_item.admin.inc',
      'controller class' => 'EntityDefaultUIController',
    ),
  );

  return $entity_info;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function line_item_entity_property_info_alter(&$info) {
  // Augment the default information that is provided by entityPropertyInfo().
  // @see EntityDefaultMetadataController::entityPropertyInfo()
  $properties = &$info['line_item']['properties'];

  $properties['type']['description'] = t('The line item type');
  $properties['type']['options list'] = 'line_item_type_get_names';
  $properties['type']['required'] = TRUE;
  $properties['type']['setter callback'] = 'entity_property_verbatim_set';
  $properties['type']['setter permission'] = 'administer line items';

  $properties['created']['label'] = t('Date created');
  $properties['created']['description'] = t('The date the line item was created.');
  $properties['created']['type'] = 'date';
  $properties['created']['setter callback'] = 'entity_property_verbatim_set';
  $properties['created']['setter permission'] = 'administer line items';

  $properties['changed']['label'] = t('Date changed');
  $properties['changed']['description'] = t('The date the line item was most recently updated.');
  $properties['changed']['type'] = 'date';

  $properties['is_new']['label'] = t('Is new');
  $properties['is_new']['description'] = t('Whether the line item is new and not saved to the database yet.');
  $properties['is_new']['type'] = 'boolean';
  $properties['is_new']['getter callback'] = 'line_item_entity_metadata_get_properties';

  $properties['bid']['label'] = t('Business');
  $properties['bid']['description'] = t('The business for which this line item was created.');
  $properties['bid']['setter callback'] = 'entity_property_verbatim_set';
  $properties['bid']['setter permission'] = 'administer line items';
  $properties['bid']['type'] = 'business';
}

/**
 * Determines whether the given user has access to a line item.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param object $line_item
 *   Optionally an line item to check access for. If nothing is given, access for
 *   all line items is determined.
 * @param object $account
 *   Optional, a user object representing the user for whom the operation is to
 *   be performed. Determines access for a user other than the current user.
 *
 * @return boolean
 *   TRUE if the operation may be performed, FALSE otherwise.
 */
function line_item_access($op, $line_item = NULL, $account = NULL) {
  if (user_access('administer line items', $account)) {
    return TRUE;
  }

  if ($op == 'create') {
    $access = user_access('create new line items', $account);
    $access |= user_access('administer own line items', $account);
    return $access;
  }

  if (!empty($line_item)) {
    switch ($op) {
      case 'delete':
      case 'update':
        $access = user_access("edit any $line_item->type line item", $account);
        $access |= user_access('administer own line items', $account) && line_item_is_owned_by_user($line_item, $account);
        return $access;

      case 'view':
        $access = user_access("view any $line_item->type line item", $account);
        $access |= user_access('view own line items', $account) && line_item_is_owned_by_user($line_item, $account);
        return $access;
    }
  }

  return FALSE;
}

/**
 * Implements hook_permission().
 */
function line_item_permission() {
  $permissions = array(
    'administer line items' => array(
      'title' => t('Administer line items'),
      'description' => t('Create new line items, and edit and delete all line items.'),
    ),
    'administer line item types' => array(
      'title' => t('Administer line item types'),
      'description' => t('Create and delete fields for line item types, and set their permissions.'),
    ),
    'create new line items' => array(
      'title' => t('Create new line items'),
    ),
    'view own line items' => array(
      'title' => t('View own line items'),
    ),
    'administer own line items' => array(
      'title' => t('Administer own line items'),
      'description' => t('Edit and delete your own line items.'),
    ),
  );

  // Generate permissions per line item type.
  foreach (line_item_get_types() as $type) {
    $permissions += array(
      "edit any $type->type line item" => array(
        'title' => t('%type_name: Edit any line item', array('%type_name' => $type->name)),
      ),
      "view any $type->type line item" => array(
        'title' => t('%type_name: View any line item', array('%type_name' => $type->name)),
      ),
    );
  }

  return $permissions;
}

/**
 * Access callback for Entity API exportables for line item types.
 */
function line_item_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer line item types', $account);
}

/**
 * Returns an array of line item types, keyed by the type name.
 *
 * @return array
 *   An associative array of line item types, keyed by line item type.
 */
function line_item_get_types() {
  $types = &drupal_static(__FUNCTION__);

  if (!$types) {
    $types = db_select('line_item_type', 'lit')
      ->fields('lit')
      ->execute()
      ->fetchAllAssoc('type');
  }

  return $types;
}

/**
 * Returns an line item type by type name.
 *
 * @param string $type
 *   The machine readable name of the line item type.
 *
 * @return Entity
 *   A line item type entity, or FALSE if the line item type does not exist.
 */
function line_item_type_load($type) {
  $types = line_item_get_types();

  return !empty($types[$type]) ? $types[$type] : FALSE;
}

/**
 * Returns a list of line item type machine names.
 *
 * @return array
 *   An indexed array of line item type machine names.
 */
function line_item_type_get_names() {
  return array_keys(line_item_get_types());
}

/**
 * Creates a new line item entity.
 *
 * @param array $values
 *   An associative array of values to apply to the entity, keyed by property
 *   name.
 *
 * @return LineItem
 *   The new line item entity.
 */
function line_item_create($values = array()) {
  if (empty($values['type'])) {
    throw new Exception(t('Invalid or missing line item bundle given.'));
  }
  return entity_get_controller('line_item')->create($values);
}

/**
 * Deletes a line item.
 *
 * @param LineItem $line_item
 *   The line item to delete.
 */
function line_item_delete(LineItem $line_item) {
  $line_item->delete();
}

/**
 * Deletes multiple line items.
 *
 * @param array $lids
 *   An array of line item IDs.
 */
function line_item_delete_multiple(array $lids) {
  entity_get_controller('line_item')->delete($lids);
}

/**
 * Composes the label of a line item.
 *
 * @see entity_label()
 *
 * @param object $entity
 *   The entity for which to generate the label.
 * @param string $entity_type
 *   The entity type; e.g., 'node' or 'user'.
 *
 * @return string|bool
 *   The entity label or FALSE if not found.
 */
function line_item_label($entity, $entity_type) {
  return $entity->lid;
}

/**
 * Saves a line item to the database.
 *
 * @param LineItem $line_item
 *   The line item entity.
 *
 * @return mixed
 *   Returns FALSE if the transaction failed. If it succeeded, returns SAVED_NEW
 *   or SAVED_UPDATED, depending on the operation performed.
 */
function line_item_save(LineItem $line_item) {
  return $line_item->save();
}

/**
 * Loads a line item object from the database.
 *
 * @param int $lid
 *   The line item ID.
 * @param bool $reset
 *   Whether to reset the cache.
 *
 * @return
 *   A fully-populated line item object, or FALSE if the line item is not found.
 *
 * @throws InvalidArgumentException
 *   Thrown when the passed ID is not valid.
 */
function line_item_load($lid, $reset = FALSE) {
  $lid = (int) $lid;
  if (empty($lid)) {
    throw new InvalidArgumentException('Invalid line item id.');
  }
  $line_items = line_item_load_multiple((array) $lid, $reset);

  return $line_items ? reset($line_items) : FALSE;
}

/**
 * Loads line items from the database.
 *
 * This function should be used whenever you need to load more than one line
 * item from the database. Line items are loaded into memory and will not
 * require database access if loaded again during the same page request.
 *
 * @see entity_load()
 * @see EntityFieldQuery
 *
 * @param $lids
 *   An array of line item IDs.
 * @param $reset
 *   Whether to reset the internal cache.
 *
 * @return
 *   An array of line item objects indexed by lid.
 */
function line_item_load_multiple($lids = array(), $reset = FALSE) {
  return entity_load('line_item', $lids, array(), $reset);
}

/**
 * Implements callback_entity_info_uri().
 */
function line_item_uri(LineItem $line_item) {
  return array(
    'path' => 'line_item/' . $line_item->lid,
  );
}

/**
 * Creates a line item type.
 *
 * @param string $type
 *   The machine readable name of the line item type.
 * @param string $name
 *   The human readable name of the line item type.
 */
function line_item_type_create($type, $name) {
  db_insert('line_item_type')
    ->fields(array(
      'type' => $type,
      'name' => $name,
    ))
    ->execute();
}

/**
 * Composes the label of a line item type.
 *
 * @see entity_label()
 *
 * @param object $entity
 *   The entity for which to generate the label.
 * @param string $entity_type
 *   The entity type; e.g., 'node' or 'user'.
 *
 * @return string|bool
 *   The entity label or FALSE if not found.
 */
function line_item_type_label($entity, $entity_type) {
  // If the entity type is being created it does not have a name yet.
  if (empty($entity->is_new)) {
    return $entity->name;
  }
  return FALSE;
}

/**
 * Returns whether a given line item is owned by a given user.
 *
 * @param LineItem $line_item
 *   The line item to check.
 * @param object $account
 *   Optional user account to check. Defaults to the currently logged in user.
 *
 * @return bool
 *   TRUE if the line item is owned by the user, FALSE otherwise.
 */
function line_item_is_owned_by_user(LineItem $line_item, stdClass $account = NULL) {
  // Default to the logged in user.
  global $user;
  $account = $account ?: $user;

  $line_item = entity_metadata_wrapper('line_item', $line_item);
  return in_array($line_item->bid->value(), array_keys(business_get_businesses_from_user($account)));
}

/**
 * Callback for getting line item properties.
 *
 * @see line_item_entity_property_info()
 */
function line_item_entity_metadata_get_properties(LineItem $line_item, array $options, $name, $entity_type, $info) {
  switch ($name) {
    case 'is_new':
      return empty($line_item->lid) || !empty($line_item->is_new);
  }
}

/**
 * The class used for line item entities.
 */
class LineItem extends Entity {

  /**
   * The primary identifier for a line item.
   */
  public $lid;

  /**
   * The type of this line item.
   */
  public $type;

  /**
   * The identifier of the business.
   */
  public $bid;

  /**
   * The Unix timestamp when the line item was created.
   */
  public $created;

  /**
   * The Unix timestamp when the line item was most recently saved.
   */
  public $changed;

  /**
   * {@inheritdoc}
   */
  public function save() {
    // Set created and changed values. Only set the created value if it is new.
    if (empty($this->created) && (!empty($this->is_new) || !$this->lid)) {
      $this->created = REQUEST_TIME;
    }
    $this->changed = REQUEST_TIME;

    return parent::save();
  }

}

/**
 * The Line Item Entity API controller class.
 */
class LineItemAPIController extends EntityAPIController {

  /**
   * {@inheritdoc}
   */
  public function create(array $values = array()) {
    // Set the business id to the active business of the logged in user.
    $business = business_get_active_business();
    if ($business instanceof Business) {
      $values += array('bid' => $business->bid);
    }
    return parent::create($values);
  }

}

/**
 * The Line Item Inline Entity Form controller class.
 */
class LineItemInlineEntityFormController extends EntityInlineEntityFormController {
}
