<?php

/**
 * @file
 * Main functions and hook implementations for the Invoicing Dashboard module.
 */

include_once 'invoicing_dashboard.features.inc';

/**
 * Implements hook_permission().
 */
function invoicing_dashboard_permission() {
  $permissions = array(
    'access invoicing dashboard' => array(
      'title' => t('Access the dashboard'),
    ),
  );

  return $permissions;
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function invoicing_dashboard_ctools_plugin_directory($module, $plugin) {
  $types = array(
    'ctools:content_types',
  );

  if (in_array("$module:$plugin", $types)) {
    return "plugins/$plugin";
  }
}
