<?php

/**
 * @file
 * Main functions and hook implementations for the Invoicing Invoice module.
 */

include_once 'invoice.features.inc';

/**
 * Implements hook_entity_info().
 */
function invoice_entity_info() {
  $entity_info = [];

  $entity_info['invoice'] = [
    'label' => t('Invoice'),
    'plural label' => t('Invoices'),
    'entity class' => 'Invoice',
    'controller class' => 'InvoiceAPIController',
    'base table' => 'invoice',
    'fieldable' => TRUE,
    'entity keys' => [
      'id' => 'iid',
      'bundle' => 'type',
    ],
    'bundle keys' => [
      'bundle' => 'type',
    ],
    'bundles' => [],
    'label callback' => 'invoice_label',
    'uri callback' => 'invoice_uri',
    'access callback' => 'invoice_access',
    'module' => 'invoice',
  ];

  // Add bundle info but bypass entity_load() as we cannot use it here.
  $types = db_select('invoice_type', 'ivt')
    ->fields('ivt', ['type', 'name'])
    ->execute()
    ->fetchAllKeyed();

  foreach ($types as $type => $name) {
    $entity_info['invoice']['bundles'][$type] = [
      'label' => $name,
      'admin' => [
        'path' => 'admin/structure/invoices/manage/%invoice_type',
        'real path' => 'admin/structure/invoices/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => ['administer invoices'],
      ],
    ];
  }

  $entity_info['invoice_type'] = [
    'label' => t('Invoice type'),
    'plural label' => t('Invoice types'),
    'entity class' => 'Entity',
    'controller class' => 'EntityAPIControllerExportable',
    'base table' => 'invoice_type',
    'fieldable' => FALSE,
    'bundle of' => 'invoice',
    'exportable' => TRUE,
    'entity keys' => [
      'id' => 'type',
      'name' => 'type',
      'label' => 'name',
    ],
    'access callback' => 'invoice_type_access',
    'label callback' => 'invoice_type_label',
    'module' => 'invoice',
    'admin ui' => [
      'path' => 'admin/structure/invoices',
      'file' => 'invoice.admin.inc',
      'controller class' => 'EntityDefaultUIController',
    ],
  ];

  return $entity_info;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function invoice_entity_property_info_alter(&$info) {
  // Augment the default information that is provided by entityPropertyInfo().
  // @see EntityDefaultMetadataController::entityPropertyInfo()
  $properties = &$info['invoice']['properties'];

  $properties['type']['description'] = t('The invoice type');
  $properties['type']['options list'] = 'invoice_type_get_names';
  $properties['type']['required'] = TRUE;
  $properties['type']['setter callback'] = 'entity_property_verbatim_set';
  $properties['type']['setter permission'] = 'administer invoices';

  $properties['created']['label'] = t('Date created');
  $properties['created']['description'] = t('The date the invoice was created.');
  $properties['created']['type'] = 'date';
  $properties['created']['setter callback'] = 'entity_property_verbatim_set';
  $properties['created']['setter permission'] = 'administer invoices';

  $properties['changed']['label'] = t('Date changed');
  $properties['changed']['description'] = t('The date the invoice was most recently updated.');
  $properties['changed']['type'] = 'date';
  $properties['changed']['setter callback'] = 'entity_property_verbatim_set';
  $properties['changed']['setter permission'] = 'administer invoices';

  $properties['is_new']['label'] = t('Is new');
  $properties['is_new']['description'] = t('Whether the invoice is new and not saved to the database yet.');
  $properties['is_new']['type'] = 'boolean';
  $properties['is_new']['getter callback'] = 'invoice_entity_metadata_get_properties';

  $properties['bid']['label'] = t('Business');
  $properties['bid']['description'] = t('The business that issued this invoice.');
  $properties['bid']['setter callback'] = 'entity_property_verbatim_set';
  $properties['bid']['setter permission'] = 'administer invoices';
  $properties['bid']['type'] = 'business';
}

/**
 * Implements hook_menu().
 */
function invoice_menu() {
  $items = [];

  // We only support one basic invoice type for the moment. This may be extended
  // in the future.
  $invoice_type = invoice_type_load('invoice');
  $items['invoice/add'] = [
    'title' => 'Add invoice',
    'page callback' => 'invoice_add_page',
    'page arguments' => [$invoice_type],
    'access callback' => 'invoice_access',
    'access arguments' => ['create', $invoice_type],
    'file' => 'invoice.pages.inc',
  ];

  $items['invoice/%invoice/edit'] = [
    'title' => 'Edit',
    'page callback' => 'invoice_edit_page',
    'page arguments' => [1],
    'access callback' => 'invoice_access',
    'access arguments' => ['update', 1],
    'type' => MENU_LOCAL_TASK,
    'file' => 'invoice.pages.inc',
    'weight' => 5,
  ];

  $items['invoice/%invoice/delete'] = [
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => ['invoice_delete_confirm_form', 1],
    'access callback' => 'invoice_access',
    'access arguments' => ['delete', 1],
    'type' => MENU_LOCAL_TASK,
    'file' => 'invoice.pages.inc',
    'weight' => 10,
  ];

  $items['invoice/%invoice/view'] = [
    'title' => 'View',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => 0,
  ];

  $items['invoice/%invoice'] = [
    'title' => '',
    'page callback' => 'invoice_detail_page',
    'page arguments' => [1],
    'access callback' => 'invoice_access',
    'access arguments' => ['view', 1],
    'type' => MENU_CALLBACK,
    'file' => 'invoice.pages.inc',
  ];

  $items['invoice/%invoice/html'] = [
    'title' => 'HTML',
    'page callback' => 'invoice_generate_html',
    'page arguments' => [1],
    // This is protected with a token in the page callback. No session based
    // access control can be done since this path needs to be accessible by the
    // PDF converter.
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'invoice.pages.inc',
  ];

  $items['invoice/%invoice/download'] = [
    'title' => 'Download',
    'page callback' => 'invoice_download',
    'page arguments' => [1],
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'invoice.pages.inc',
  ];

  return $items;
}

/**
 * Determines whether the given user has access to an invoice.
 *
 * @param string $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param \stdClass|Invoice $invoice
 *   Optionally an invoice to check access for. If nothing is given, access for
 *   all invoices is determined. This can be either a full Invoice object, or,
 *   when a new invoice is being created, an object containing menu access
 *   arguments.
 * @param object $account
 *   Optional, a user object representing the user for whom the operation is to
 *   be performed. Determines access for a user other than the current user.
 *
 * @return bool
 *   TRUE if the operation may be performed, FALSE otherwise.
 */
function invoice_access($op, $invoice = NULL, $account = NULL) {
  // Administrators can do anything except creating new invoices, since they do
  // not own a business.
  if (user_access('administer invoices', $account)) {
    return $op !== 'create';
  }

  if (isset($invoice)) {
    switch ($op) {
      case 'create':
        return user_access('create new invoices', $account);

      case 'delete':
      case 'edit':
      case 'update':
        $access = user_access("edit any $invoice->type invoice", $account);
        $access |= user_access('administer own invoices', $account) && invoice_is_owned_by_user($invoice, $account);
        return $access;

      case 'view':
        $access = user_access("view any $invoice->type invoice", $account);
        $access |= user_access('view own invoices', $account) && invoice_is_owned_by_user($invoice, $account);
        return $access;
    }
  }

  return FALSE;
}

/**
 * Implements hook_permission().
 */
function invoice_permission() {
  $permissions = [
    'access invoice overview' => [
      'title' => t('Access invoice overview'),
    ],
    'administer invoices' => [
      'title' => t('Administer invoices'),
      'description' => t('Create new invoices, and edit and delete all invoices.'),
    ],
    'administer invoice types' => [
      'title' => t('Administer invoice types'),
      'description' => t('Create and delete fields for invoice types, and set their permissions.'),
    ],
    'create new invoices' => [
      'title' => t('Create new invoices'),
    ],
    'view own invoices' => [
      'title' => t('View own invoices'),
    ],
    'administer own invoices' => [
      'title' => t('Administer own invoices'),
      'description' => t('Edit and delete your own invoices.'),
    ],
    'view html version of any invoice' => [
      'title' => t('View HTML version of any invoice'),
      'description' => t('This is intended to help in developing and theming PDF templates.'),
    ],
  ];

  // Generate permissions per invoice type.
  foreach (invoice_get_types() as $type) {
    $permissions += [
      "edit any $type->type invoice" => [
        'title' => t('%type_name: Edit any invoice', ['%type_name' => $type->name]),
      ],
      "view any $type->type invoice" => [
        'title' => t('%type_name: View any invoice', ['%type_name' => $type->name]),
      ],
    ];
  }

  return $permissions;
}

/**
 * Implements hook_theme().
 */
function invoice_theme($existing, $type, $theme, $path) {
  return [
    'invoice_export' => [
      'variables' => ['invoice' => NULL],
      'template' => 'invoice_export',
      'path' => drupal_get_path('module', 'invoice') . '/theme',
    ],
    'invoice_totals' => [
      'variables' => ['invoice' => NULL],
    ],
    'invoice_inline_client_entity' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Process variables for invoice templates that will be exported to PDF.
 *
 * @param array $vars
 *   An associative array with the following keys:
 *   - 'invoice': contains the Invoice entity that will be rendered.
 */
function template_preprocess_invoice_export(array &$vars) {
  $invoice_entity = $vars['invoice'];
  $invoice = entity_metadata_wrapper('invoice', $invoice_entity);

  // Make all invoice properties available.
  $vars['invoice_client'] = field_view_field('invoice', $invoice_entity, 'field_invoice_client');
  $vars['invoice_date'] = field_view_field('invoice', $invoice_entity, 'field_invoice_date');
  $vars['invoice_discount'] = field_view_field('invoice', $invoice_entity, 'field_invoice_discount');
  $vars['invoice_due_date'] = field_view_field('invoice', $invoice_entity, 'field_invoice_due_date');
  $vars['invoice_number'] = field_view_field('invoice', $invoice_entity, 'field_invoice_number');
  $vars['invoice_po_number'] = field_view_field('invoice', $invoice_entity, 'field_invoice_po_number');
  $vars['invoice_products'] = field_view_field('invoice', $invoice_entity, 'field_invoice_products');
  $vars['invoice_services'] = field_view_field('invoice', $invoice_entity, 'field_invoice_services');
  $vars['invoice_terms'] = field_view_field('invoice', $invoice_entity, 'field_invoice_terms');

  // Provide the full business entity that issued the invoice as a variable.
  $business_entity = $invoice->bid->value();
  $vars['business'] = $business_entity;
  $business = entity_metadata_wrapper('business', $business_entity);

  // Make all business properties available.
  $vars['business_name'] = $business->name->value(['sanitize' => TRUE]);
  $vars['business_address'] = field_view_field('business', $business_entity, 'field_business_address');
  $vars['business_address']['#title'] = t('Address');
  $vars['business_bic'] = field_view_field('business', $business_entity, 'field_business_bic');
  $vars['business_email'] = field_view_field('business', $business_entity, 'field_business_email');
  $vars['business_iban'] = field_view_field('business', $business_entity, 'field_business_iban');
  $vars['business_mobile'] = field_view_field('business', $business_entity, 'field_business_mobile');
  $vars['business_phone'] = field_view_field('business', $business_entity, 'field_business_phone');
  $vars['business_vat'] = field_view_field('business', $business_entity, 'field_business_vat');

  // Provide the full client entity as a variable.
  $client_entity = $invoice->field_invoice_client->value();
  $vars['client'] = $client_entity;
  $client = entity_metadata_wrapper('client', $client_entity);

  // Make all client properties available.
  $vars['client_name'] = $client->name->value(['sanitize' => TRUE]);
  $vars['client_address'] = field_view_field('client', $client_entity, 'field_client_address');
  $vars['client_address']['#title'] = t('Address');
  $vars['client_email'] = field_view_field('client', $client_entity, 'field_client_email');
  $vars['client_phone'] = field_view_field('client', $client_entity, 'field_client_phone');
  $vars['client_shipping_address'] = field_view_field('client', $client_entity, 'field_client_shipping_address');
  $vars['client_vat'] = field_view_field('client', $client_entity, 'field_client_vat');
  $vars['client_website'] = field_view_field('client', $client_entity, 'field_client_website');

  // Provide the tables for products and services.
  $vars['products'] = views_embed_view('line_items', 'products', $invoice_entity->identifier());
  $vars['services'] = views_embed_view('line_items', 'services', $invoice_entity->identifier());

  // Provide a table with the totals.
  $vars['totals'] = theme('invoice_totals', ['invoice' => $invoice_entity]);

  // Provide a list of CSS files.
  // @todo Generate this with drupal_get_css() when we have PDF templates.
  $css_path = drupal_get_path('module', 'invoice') . '/theme/invoice_export.css';
  $css_url = url($css_path, ['absolute' => TRUE]);
  $vars['styles'] = <<<HTML
    <style type="text/css" media="all">@import url("$css_url");</style>
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu">
HTML;

  // @todo Render CSS styles inline. On Travis wkhtmltopdf cannot access these
  //   external stylesheets and hangs.
  // @see https://github.com/pfrenssen/invoicing/issues/48
  $vars['styles'] = '';
}

/**
 * Access callback for Entity API exportables for invoice types.
 */
function invoice_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer invoice types', $account);
}

/**
 * Returns an array of invoice types, keyed by the type name.
 *
 * @return array
 *   An associative array of invoice types, keyed by invoice type.
 */
function invoice_get_types() {
  $types = &drupal_static(__FUNCTION__);

  if (!$types) {
    $types = db_select('invoice_type', 'ivt')
      ->fields('ivt')
      ->execute()
      ->fetchAllAssoc('type');
  }

  return $types;
}

/**
 * Returns an invoice type by type name.
 *
 * @param string $type
 *   The machine readable name of the invoice type.
 *
 * @return Entity
 *   A invoice type entity, or FALSE if the invoice type does not exist.
 */
function invoice_type_load($type) {
  $types = invoice_get_types();

  return !empty($types[$type]) ? $types[$type] : FALSE;
}

/**
 * Returns a list of invoice type names.
 *
 * @return array
 *   An associative array of invoice type labels, keyed by invoice type.
 */
function invoice_type_get_names() {
  $types = [];

  foreach (invoice_get_types() as $machine_name => $type) {
    $types[$machine_name] = $type->name;
  }

  return $types;
}

/**
 * Composes the label of an invoice type.
 *
 * @param Entity $invoice
 *   The invoice for which to generate the label.
 *
 * @return string|bool
 *   The entity label or FALSE if not found.
 *
 * @see entity_label()
 */
function invoice_type_label(Entity $invoice) {
  // If the entity type is being created it does not have a name yet.
  if (empty($invoice->is_new)) {
    return $invoice->name;
  }
  return FALSE;
}

/**
 * Creates a new invoice entity.
 *
 * @param array $values
 *   An associative array of values to apply to the entity, keyed by property
 *   name.
 *
 * @return Invoice
 *   The new invoice entity.
 */
function invoice_create($values = []) {
  // Default to the 'invoice' bundle.
  $values += ['type' => 'invoice'];
  return entity_get_controller('invoice')->create($values);
}

/**
 * Deletes a invoice.
 *
 * @param Invoice $invoice
 *   The invoice to delete.
 */
function invoice_delete(Invoice $invoice) {
  $invoice->delete();
}

/**
 * Deletes multiple invoices.
 *
 * @param array $iids
 *   An array of invoice IDs.
 */
function invoice_delete_multiple(array $iids) {
  entity_get_controller('invoice')->delete($iids);
}

/**
 * Composes the label of an Invoice.
 *
 * @param object $entity
 *   The entity for which to generate the label.
 * @param string $entity_type
 *   The entity type; e.g., 'node' or 'user'.
 *
 * @return string|bool
 *   The entity label or FALSE if not found.
 *
 * @see entity_label()
 */
function invoice_label($entity, $entity_type) {
  return $entity->iid;
}

/**
 * Saves a invoice to the database.
 *
 * @param Invoice $invoice
 *   The invoice entity.
 *
 * @return mixed
 *   Returns FALSE if the transaction failed. If it succeeded, returns SAVED_NEW
 *   or SAVED_UPDATED, depending on the operation performed.
 */
function invoice_save(Invoice $invoice) {
  return $invoice->save();
}

/**
 * Loads an invoice object from the database.
 *
 * @param int $iid
 *   The invoice ID.
 * @param bool $reset
 *   Whether to reset the cache.
 *
 * @return Invoice|FALSE
 *   A fully-populated invoice object, or FALSE if the invoice is not found.
 *
 * @throws InvalidArgumentException
 *   Thrown when the passed ID is not valid.
 */
function invoice_load($iid, $reset = FALSE) {
  $iid = (int) $iid;
  if (empty($iid)) {
    throw new InvalidArgumentException('Invalid invoice id.');
  }
  $invoices = invoice_load_multiple((array) $iid, $reset);

  return $invoices ? reset($invoices) : FALSE;
}

/**
 * Loads invoices from the database.
 *
 * This function should be used whenever you need to load more than one invoice
 * from the database. Invoices are loaded into memory and will not require
 * database access if loaded again during the same page request.
 *
 * @param array $iids
 *   An array of invoice IDs.
 * @param bool $reset
 *   Whether to reset the internal cache.
 *
 * @return array
 *   An array of invoice objects indexed by iid.
 *
 * @see entity_load()
 * @see EntityFieldQuery
 */
function invoice_load_multiple($iids = [], $reset = FALSE) {
  return entity_load('invoice', $iids, [], $reset);
}

/**
 * Implements callback_entity_info_uri().
 */
function invoice_uri(Invoice $invoice) {
  return [
    'path' => 'invoice/' . $invoice->iid,
  ];
}

/**
 * Creates a invoice type.
 *
 * @param string $type
 *   The machine readable name of the invoice type.
 * @param string $name
 *   The human readable name of the invoice type.
 */
function invoice_type_create($type, $name) {
  db_insert('invoice_type')
    ->fields([
      'type' => $type,
      'name' => $name,
    ])
    ->execute();
}

/**
 * Callback for getting invoice properties.
 *
 * @see invoice_entity_property_info()
 */
function invoice_entity_metadata_get_properties(Invoice $invoice, array $options, $name, $entity_type, $info) {
  switch ($name) {
    case 'is_new':
      return empty($invoice->iid) || !empty($invoice->is_new);
  }
}

/**
 * Returns whether a given invoice is owned by a given user.
 *
 * @param Invoice $invoice
 *   The invoice to check.
 * @param \stdClass $account
 *   Optional user account to check. Defaults to the currently logged in user.
 *
 * @return bool
 *   TRUE if the invoice is owned by the user, FALSE otherwise.
 */
function invoice_is_owned_by_user(Invoice $invoice, \stdClass $account = NULL) {
  // Default to the logged in user.
  global $user;
  $account = $account ?: $user;

  return in_array($invoice->bid, array_keys(business_get_businesses_from_user($account)));
}

/**
 * Get the invoice IDs for a specific user, defaults to the logged in user.
 *
 * @param \stdClass $account
 *   The account of the user to get the invoice IDs for. If omitted, the logged
 *   in user will be used.
 * @param bool $reset
 *   Whether or not to reset the static cache. Defaults to FALSE.
 *
 * @return array
 *   An array with all the invoice IDs linked to this user. When no invoices are
 *   found an empty array will be returned.
 */
function invoice_get_invoice_ids_from_user(\stdClass $account = NULL, $reset = FALSE) {
  $bids = business_get_business_ids_from_user($account, $reset);

  $iids = &drupal_static(__FUNCTION__, []);
  if (empty($iids[$account->uid]) || $reset) {
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'invoice')
      ->propertyCondition('bid', $bids, 'IN');
    $result = $query->execute();

    $iids[$account->uid] = !empty($result['invoice']) ? array_keys($result['invoice']) : [];
  }

  return $iids[$account->uid];
}

/**
 * Get the invoices for a specific user, defaults to the logged in user.
 *
 * @param \stdClass $account
 *   The account of the user to get the invoices for. If omitted, the logged in
 *   user will be used.
 * @param bool $reset
 *   Whether or not to reset the static cache. Defaults to FALSE.
 *
 * @return Invoice[]
 *   An array with all the invoices linked to this user. When no invoices are
 *   found an empty array will be returned.
 */
function invoice_get_invoices_from_user(\stdClass $account = NULL, $reset = FALSE) {
  $iids = invoice_get_invoice_ids_from_user($account, $reset);
  return invoice_load_multiple($iids);
}

/**
 * Retrieve the most recent invoice of a business.
 *
 * @param int $bid
 *   Optional business ID of the business for which to retrieve the invoice.
 *   Defaults to the active business.
 * @param bool $reset
 *   Whether or not to reset the static cache.
 *
 * @return \Invoice
 *   The most recent invoice.
 *
 * @throws \NoInvoiceException
 *   Thrown when the active business does not have any invoices yet, or when the
 *   invoice could not be loaded.
 * @throws \NoActiveBusinessException
 *   Thrown when there is not active business.
 * @throws \InvoiceNotFoundException
 *   Thrown when an invoice number was present in the database but the invoice
 *   could not be loaded.
 */
function invoice_get_most_recent_invoice($bid = NULL, $reset = FALSE) {
  // Default to the active business.
  if (!$bid) {
    if (!$business = business_get_active_business()) {
      throw new \NoActiveBusinessException('Cannot retrieve the most recent invoice without an active business.');
    }
    $bid = $business->identifier();
  }

  $iids = &drupal_static(__FUNCTION__, []);
  if (!isset($iids[$bid]) || $reset) {
    $query = new EntityFieldQuery();
    $query
      ->entityCondition('entity_type', 'invoice')
      ->propertyCondition('bid', $bid)
      ->entityOrderBy('entity_id', 'DESC')
      ->range(0, 1);
    $result = $query->execute();

    if (!empty($result['invoice'])) {
      reset($result['invoice']);
      $iids[$bid] = key($result['invoice']);
    }
    else {
      $iids[$bid] = FALSE;
    }
  }

  // Throw exceptions when an unexpected condition occurred.
  if (empty($iids[$bid])) {
    throw new NoInvoiceException('Cannot retrieve the most recent invoice, the business has no invoices.');
  }
  if (!$invoice = invoice_load($iids[$bid])) {
    throw new InvoiceNotFoundException("The invoice with number '$bid' could not be loaded.");
  }

  return $invoice;
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function invoice_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  switch ($root_path) {
    // Add action link to 'invoice/add' on the invoices overview.
    case 'invoices':
      $action = menu_get_item('invoice/add');
      break;

    // Add links to the invoice detail page to download a PDF and view the HTML
    // version.
    case 'invoice/%':
      $invoice = menu_get_object('invoice');

      // Add an action link to download a PDF.
      $action = menu_get_item('invoice/' . $invoice->identifier() . '/download');
      $action['localized_options'] = [
        'attributes' => ['class' => 'download'],
        'query' => ['token' => drupal_get_token('invoice-download-link-' . $invoice->identifier())],
      ];

      // Add a tab to view the HTML version for administrators. This is mainly
      // intended to help in theming and debugging.
      $tab = menu_get_item('invoice/' . $invoice->identifier() . '/html');
      $tab['localized_options'] = [
        'query' => ['token' => invoice_get_token($invoice)],
      ];
      $tab['access'] = user_access('view html version of any invoice');
      break;
  }

  if (isset($action) && $action['access']) {
    $data['actions']['output'][] = [
      '#theme' => 'menu_local_action',
      '#link' => $action,
    ];
  }

  if (isset($tab) && $tab['access']) {
    $data['tabs'][0]['output'][] = [
      '#theme' => 'menu_local_action',
      '#link' => $tab,
    ];
  }
}

/**
 * Generates a non-session-safe token for an invoice.
 *
 * This is based on drupal_get_token() but is not taking the user session into
 * account. These tokens are used to protect the HTML versions of the invoices
 * at invoice/%/html. The PDF converter needs to be able to access these paths
 * without having a user session.
 *
 * This is reasonably safe because the tokens are never exposed to end users and
 * are calculated using data that is not available to the users.
 *
 * >> These tokens should never be used on any page accessible by end users! <<
 *
 * @param Invoice $invoice
 *   The invoice to base the token on.
 *
 * @return string
 *   A 43-character URL-safe token based on the invoice, the hash salt provided
 *   by drupal_get_hash_salt(), and the 'drupal_private_key' configuration
 *   variable.
 *
 * @see drupal_get_token()
 */
function invoice_get_token(Invoice $invoice) {
  return drupal_hmac_base64($invoice->identifier() . $invoice->created . $invoice->changed, drupal_get_private_key() . drupal_get_hash_salt());
}

/**
 * Retrieves the default invoice number to use for a new invoice.
 *
 * This will be the number of the most recent invoice increased by one.
 *
 * @param string $entity_type
 *   The type of $entity; e.g., 'node' or 'user'.
 * @param \Invoice $entity
 *   The entity for the operation.
 * @param array $field
 *   The field structure.
 * @param array $instance
 *   The instance structure.
 * @param string $langcode
 *   The field language to fill-in with the default value.
 *
 * @return array
 *   The default value for the invoice number.
 */
function invoice_get_default_number($entity_type, \Invoice $entity, array $field, array $instance, $langcode) {
  try {
    $invoice = invoice_get_most_recent_invoice();
    $previous_number = $invoice->wrapper()->field_invoice_number->value();
    return [['value' => invoice_increment_number($previous_number)]];
  }
  catch (\NoInvoiceException $e) {
    // If there is no invoice yet, let the user decide on a number.
    return NULL;
  }
}

/**
 * Returns the invoice number that follows the given invoice number.
 *
 * Only the numbers are incremented, not any other symbols. If there are no more
 * numbers to increment the first number will be prefixed with a 1.
 *
 * @param string $invoice_number
 *   The invoice number to increment.
 *
 * @return string
 *   The incremented invoice number.
 */
function invoice_increment_number($invoice_number) {
  // Iterate backwards through the characters in the invoice number.
  for ($i = strlen($invoice_number) - 1; $i >= 0; $i--) {
    if (is_numeric($invoice_number[$i])) {
      // Keep track of the most significant number so we can prefix it with a
      // '1' if it overflows.
      $most_significant_number = $i;

      // If the number is lower than 9, increase it and stop iterating.
      if ($invoice_number[$i] < 9) {
        $invoice_number[$i] = $invoice_number[$i] + 1;
        break;
      }
      // The number was a 9, set it to zero and continue.
      $invoice_number[$i] = 0;
    }
  }

  // If the most significant number was set to a zero it has overflowed so we
  // need to prefix it with a '1'.
  if (isset($most_significant_number) && $invoice_number[$most_significant_number] === '0') {
    $invoice_number = substr_replace($invoice_number, '1', $most_significant_number, 0);
  }

  return $invoice_number;
}

/**
 * Implements hook_field_widget_inline_entity_form_single_form_alter().
 *
 * @todo This needs to be updated after start using the ief_autocomplete module
 * because this will be replaced.
 */
function invoice_field_widget_inline_entity_form_single_form_alter(&$element, &$form_state, $context) {
  if (!empty($context['field']) && !empty($context['field']['field_name']) && $context['field']['field_name'] == 'field_invoice_client') {
    $element['entities']['#theme'] = 'invoice_inline_client_entity';
  }
}

/**
 * Themes a table containing the invoice totals.
 */
function theme_invoice_totals($variables) {
  /** @var Invoice $invoice */
  $invoice = $variables['invoice'];

  $get_row = function ($label, $value, $class, $header = FALSE) use ($invoice) {
    $label_row = [
      'data' => $label,
      'class' => ['label'],
    ];
    $value_row = [
      'data' => $value . '&euro;',
      'class' => ['value'],
    ];
    if ($header) {
      $label_row['header'] = TRUE;
      $value_row['header'] = TRUE;
    }
    return [
      'data' => [$label_row, $value_row],
      'class' => [$class],
    ];
  };

  $rows = [];

  // Only show the base price if there are any discounts.
  if ($invoice->isDiscounted()) {
    $rows[] = $get_row(t('Base price'), $invoice->getBasePrice(), 'base-price');
  };

  // Add the line item discount.
  if ($invoice->getLineItemsDiscount() != '0.00') {
    $rows[] = $get_row(t('Discount'), $invoice->getLineItemsDiscount(), 'line-items-discount');
  }

  // Add the invoice discount.
  if ($invoice->getInvoiceDiscount() != '0.00') {
    $discount_percent = $invoice->getDiscountPercent() * 100;
    $args = ['@discount' => $discount_percent];
    $rows[] = $get_row(t('Discount @discount%', $args), $invoice->getLineItemsDiscount(), 'invoice-discount');
  }

  // Show the subtotal.
  $rows[] = $get_row(t('Subtotal'), $invoice->getSubTotal(), 'subtotal');

  // Show the taxes.
  if ($invoice->getTaxTotal() !== '0.00') {
    foreach ($invoice->getTaxes() as $tax_rate => $tax_value) {
      $args = ['@tax' => $tax_rate];
      $rows[] = $get_row(t('Tax @tax%', $args), $tax_value, 'tax-rate');
    }
  }
  // Show an empty line for the VAT if there are no taxes.
  else {
    $rows[] = $get_row(t('VAT'), '0.00', 'tax-rate');
  }

  // Add the final total.
  $rows[] = $get_row(t('Total'), $invoice->getTotal(), 'total', TRUE);

  $attributes = ['id' => 'totals'];
  return theme('table', ['rows' => $rows, 'attributes' => $attributes]);
}

/**
 * Themes the client in the invoice edit.
 */
function theme_invoice_inline_client_entity($variables) {
  if (!empty($variables['form'][0]) && !empty($variables['form'][0]['#entity'])) {
    $summary = entity_view('client', [$variables['form'][0]['#entity']], 'summary');
    $output = array_merge($summary, $variables['form'][0]['actions']);
    return drupal_render($output);
  }
}

/**
 * The class used for invoice entities.
 *
 * @property array $field_invoice_client
 * @property array $field_invoice_date
 * @property array $field_invoice_discount
 * @property array $field_invoice_due_date
 * @property array $field_invoice_number
 * @property array $field_invoice_po_number
 * @property array $field_invoice_products
 * @property array $field_invoice_services
 * @property array $field_invoice_status
 * @property array $field_invoice_terms
 */
class Invoice extends Entity {

  /**
   * The primary identifier for an invoice.
   */
  public $iid;

  /**
   * The type of this invoice.
   */
  public $type;

  /**
   * The identifier of the business.
   */
  public $bid;

  /**
   * The Unix timestamp when the invoice was created.
   */
  public $created;

  /**
   * The Unix timestamp when the invoice was most recently saved.
   */
  public $changed;

  /**
   * {@inheritdoc}
   */
  public function save() {
    // Set created and changed values. Only set the created value if it is new.
    if (empty($this->created) && (!empty($this->is_new) || !$this->iid)) {
      $this->created = REQUEST_TIME;
    }
    $this->changed = REQUEST_TIME;

    $return = parent::save();

    // The 'discount' field is casted to a float by number_field_presave().
    // Ensure the type is consistent with the value as loaded from the database
    // by casting it back to a string with two decimal numbers.
    // @see number_field_presave()
    if (isset($this->field_invoice_discount[LANGUAGE_NONE][0]['value'])) {
      $this->field_invoice_discount[LANGUAGE_NONE][0]['value'] = number_format($this->field_invoice_discount[LANGUAGE_NONE][0]['value'], 2);
    }

    // Delete the cached PDF if it exists.
    $file_uri = file_build_uri('invoices/' . $this->iid . '.pdf');
    if (file_exists($file_uri)) {
      unlink($file_uri);
    }

    return $return;
  }

  /**
   * Returns the discount percentage of the invoice.
   *
   * @return string
   *   The discount as a value with 8 decimals.
   */
  public function getDiscountPercent() {
    $discount = !empty($this->field_invoice_discount[LANGUAGE_NONE][0]['value']) ? $this->field_invoice_discount[LANGUAGE_NONE][0]['value'] : '0.00';
    return bcdiv($discount, 100, 8);
  }

  /**
   * Calculates the total price excluding VAT of an invoice.
   *
   * @return string
   *   The total excluding the VAT.
   */
  public function getSubTotal() {
    return $this->getTotals()['subtotal'];
  }

  /**
   * Calculates the total price including VAT of an invoice.
   *
   * @return string
   *   The total including the VAT.
   */
  public function getTotal() {
    return $this->getTotals()['total'];
  }

  /**
   * Returns the sum of all taxes on the invoice.
   *
   * @return string
   *   The tax total.
   */
  public function getTaxTotal() {
    $tax_total = '0.00';
    foreach ($this->getTotals()['tax'] as $tax_amount) {
      $tax_total = bcadd($tax_total, $tax_amount, 2);
    }
    return $tax_total;
  }

  /**
   * Returns an array of the taxes on the invoice.
   *
   * @return array
   *   An associative array of taxes, keyed by tax rate.
   */
  public function getTaxes() {
    return $this->getTotals()['tax'];
  }

  /**
   * Returns the total of all line items excluding discounts and taxes.
   *
   * @return string
   *   The base price.
   */
  public function getBasePrice() {
    return $this->getTotals()['base_price'];
  }

  /**
   * Returns whether or not the invoice is discounted.
   *
   * @return bool
   *   TRUE if the invoice has a discount.
   */
  public function isDiscounted() {
    return $this->getInvoiceDiscount() !== '0.00' || $this->getLineItemsDiscount() != '0.00';
  }

  /**
   * Returns the sum of all discounts on line items.
   *
   * @return string
   *   The total discount on all line items.
   */
  public function getLineItemsDiscount() {
    return $this->getTotals()['discount']['line_items'];
  }

  /**
   * Returns the global invoice discount.
   *
   * @return string
   *   The invoice discount.
   */
  public function getInvoiceDiscount() {
    return $this->getTotals()['discount']['invoice'];
  }

  /**
   * Returns the totals for an invoice.
   *
   * All values are expressed with 2 decimal numbers to represent Euros and
   * cents. They are returned as strings to avoid rounding errors with floating
   * point numbers.
   *
   * @return array
   *   An associative array containing the calculated totals, with the following
   *   keys:
   *   - 'base_price': The base price for the calculation, the total of all line
   *     items excluding discounts and taxes.
   *   - 'discount': An associative array of calculated discounts, with keys:
   *     - 'line_items': total of discounts per line item.
   *     - 'invoice': the global discount on the invoice.
   *   - 'subtotal': The total price before tax, with the discounts applied.
   *   - 'tax': The amounts of value added tax. This is an associative array of
   *     all different tax rates that were applied, keyed by tax rate.
   *   - 'total': The final total.
   */
  public function getTotals() {
    $totals = [
      'base_price' => '0.00',
      'discount' => [
        'line_items' => '0.00',
        'invoice' => '0.00',
      ],
      'subtotal' => '0.00',
      'tax' => [],
      'total' => '0.00',
    ];

    // Sum up the base price, discount and tax of the line items.
    $invoice_discount = bcsub('1.00', $this->getDiscountPercent(), 8);
    foreach ($this->getLineItems() as $line_item) {
      $line_item_totals = line_item_calculate($line_item);
      $totals['base_price'] = bcadd($totals['base_price'], $line_item_totals['base_price'], 2);
      $totals['discount']['line_items'] = bcadd($totals['discount']['line_items'], $line_item_totals['discount'], 2);

      $tax_rate = $line_item->getTaxRate();
      if (empty($totals['tax'][$tax_rate])) {
        $totals['tax'][$tax_rate] = '0.00';
      }
      // Apply the invoice discount to the tax rate. The line item discount has
      // already been applied in line_item_calculate().
      $tax_amount = number_format(bcmul($line_item_totals['tax'], $invoice_discount, 3), 2, '.', '');
      $totals['tax'][$tax_rate] = bcadd($totals['tax'][$tax_rate], $tax_amount, 2);
    }

    // Calculate the invoice discount using BCMath for financial calculations.
    // We calculate to a precision of 3 decimal numbers, then round to 2 decimal
    // numbers to get the exact value in Euros and cents.
    $discounted_base_price = bcsub($totals['base_price'], $totals['discount']['line_items'], 2);
    $totals['discount']['invoice'] = number_format(bcmul($this->getDiscountPercent(), $discounted_base_price, 3), 2, '.', '');

    // Calculate the subtotal. This is the total price before tax, with all the
    // discounts applied.
    $totals['subtotal'] = bcsub($discounted_base_price, $totals['discount']['invoice'], 2);

    // Calculate the final total by adding the taxes to the subtotal.
    $tax_total = '0.00';
    foreach ($totals['tax'] as $tax_amount) {
      $tax_total = bcadd($tax_total, $tax_amount, 2);
    }

    $totals['total'] = bcadd($totals['subtotal'], $tax_total, 2);

    return $totals;
  }

  /**
   * Returns an array of line items.
   *
   * @param string $line_item_type
   *   The type of line items to return, either 'product' or 'service'. If left
   *   empty both are returned.
   *
   * @return LineItem[]
   *   The line items.
   */
  public function getLineItems($line_item_type = NULL) {
    $line_items = [];
    foreach (['product', 'service'] as $type) {
      if (empty($line_item_type) || $line_item_type === $type) {
        $field_name = "field_invoice_{$type}s";
        if (!empty($this->{$field_name}[LANGUAGE_NONE])) {
          foreach ($this->{$field_name}[LANGUAGE_NONE] as $reference) {
            $line_items[] = line_item_load($reference['target_id']);
          }
        }
      }
    }

    return $line_items;
  }

}

/**
 * The Invoice Entity API controller class.
 */
class InvoiceAPIController extends EntityAPIController {

  /**
   * {@inheritdoc}
   */
  public function create(array $values = []) {
    // Set the business id to the active business of the logged in user.
    $business = business_get_active_business();
    if ($business instanceof Business) {
      $values += ['bid' => $business->bid];
    }
    return parent::create($values);
  }

}

/**
 * Exception thrown when the logic requires an invoice but none are present.
 */
class NoInvoiceException extends \LogicException {
}

/**
 * Thrown when an invoice with a certain ID cannot be found.
 */
class InvoiceNotFoundException extends \LogicException {
}
